### ISSUE TITLE
csmPPI.py doesn't work under py3

### ISSUE THREAD

**Issue by fzahle** [FUSED-Wind/fusedwind-unicorn#1]

**Comment by dykesk** [comment]
are you sure you are accessing the right version of csmPPI and not a legacy version?  it is working for me.

**Comment by fzahle** [comment]
Yes, its setup in an isolated conda env. I'm getting this error:

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 710: invalid start byte

**Comment by dykesk** [comment]
to make the code work (in the rush for the tutorial), i had just commented out the python 3 incompatible print statements - this worked for me, but did not work for folks using mac/linux.  during tutorial we did a hack to fix this, but i can't find the file - i've now gone through and fixed all the print statements - see  c22c16f

**Comment by fzahle** [comment]
no the issue comes from reading the static database:

    File "/Users/frza/git/fusedwind-unicorn/fusedwind/examples/csmPPI.py", line 145, in __init__
        for line in infile:
    File "/opt/miniconda/envs/fw2/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 710: invalid start byte

**Comment by fzahle** [comment]
but it works in py2. If I change the open statement to `rb` the error disappears, but then everything looked up in the PPI are zero.
